Controllers films users
xakepon/java-filmorate pull request #5
Opened 2024-02-21 13:48 UTC by xakepon

2024-02-22 06:51 UTC, LexLippi requested changes
Привет!

Неплохая работа!

НО:
- не увидел тестов на граничные случаи валидации
- есть некоторые замечания, которые необходимо исправить!

Желаю удачи!

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
В таких случаях всегда предлагаю заинлайнить инициализацию, и не реализовывать явно пустой конструктор

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.INTERNAL_SERVER_ERROR);
А почему здесь `INTERNAL_SERVER_ERROR`, а не `BAD_REQUEST`?

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return new ResponseEntity<>(user, HttpStatus.NOT_FOUND);
Почему тут в каждом контроллере новые статусы?)

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController() {
Про это писал в `FilmController`

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long duration; // продолжительность фильма
Можно использовать `java.time.Duration`

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static int FILM_ID = 0;
Луше не делать это поле статическим. Если вдруг нам понадобится два экземпляра сервиса в рамках нашего приложения, то из-за статичности этого поля это сделать не получится

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
Может быть нам объединить эти две проверки в один метод?

2024-02-22 06:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Замечания аналогичные `FilmService`

2024-02-22 11:02 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
сделал

2024-02-22 11:03 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.INTERNAL_SERVER_ERROR);
сделал

2024-02-22 11:03 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return new ResponseEntity<>(user, HttpStatus.NOT_FOUND);
думал больше подходят именно эти ,сделал BAD_REQUEST

2024-02-22 11:04 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController() {
сделал

2024-02-22 11:49 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long duration; // продолжительность фильма
сделал. единственное как с помощью  javax.validation.constraints сейчас это проверить до конца не понял

2024-02-22 11:51 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static int FILM_ID = 0;
сделал

2024-02-22 11:56 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
сделал, плюс добавил проверку что продолжительность фильма больше нуля

2024-02-22 12:11 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
из оставшегося объединил проверки

2024-02-22 14:17 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.INTERNAL_SERVER_ERROR);
в общем вернул, тесты постмана требуют ответ 500, из-за этого так

2024-02-22 14:17 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long duration; // продолжительность фильма
пришлось обратиться к гуру чтобы решить вопрос, сам бы низа что не разобрался...

2024-02-23 06:35 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-02-23 07:56 UTC, merged