Add database
xakepon/java-filmorate pull request #7
Opened 2024-04-20 16:02 UTC by xakepon

2024-04-25 09:47 UTC, LexLippi requested changes
Привет!

Неплохая работа, есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +INSERT INTO motion_picture_association (MPA_name) VALUES
1. Лучше использовать оператор `merge`
2. Лучше разбить на две разные миграции создание схемы данных и начальную инициализацию

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +INSERT INTO genres (genre_name) VALUES
Аналогично тому, что писал ниже

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS genres, MPA_ids, film, motion_picture_association, film_genres, users, likes, friends;
От этого кода необходимо избавиться. 
Кто захочет пользоваться приложением, где пользовательские данные удаляются при каждом обновлении?

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +    genre_name varchar
1. `not null`
2. Стоит установить ограничение на размер поля

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +    MPA_name varchar
Аналогично тому, что написал для таблицы жанров

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +    MPA_id integer
`not null` и ограничения где это необходимо, для даты релиза можно задать ограничения, что она должна быть больше, чем заданная дата, продолжительность должна быть положительной

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +    mpa_id integer,
`not null`

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
таблице не хватает первичного ключа

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_genres (
Замечания аналогичные `MPA_ids`

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Аналогичные замечания, что и в таблице фильмов

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS likes (
Аналогичные замечания, что и для `MPA_ids`

2024-04-25 09:47 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS friends (
Аналогичные замечания, что и для `MPA_ids`

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/validate/ErrorHandler.java
> +    //@ResponseStatus(HttpStatus.BAD_REQUEST)
удалить, если не используется

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Override
Стоит избавиться от `InMemory` хранилищ, чтобы не поддерживать их в дальнейшем

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        checkFilm(film.getId());
Можно обойтись без этой проверки, любой запрос в СУБД существенно бьет по эффективности приложения, и увеличивает нагрузку на СУБД, поэтому необходимо избешать лишних запросов. `jdbcTemplate.update` возвращает количество строк на который повлиял, если таких строк 0, то записи не было и можно выбросить ошибку, таким образом сэкономив на запросе.

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        return updatedFilm.orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));
Зачем вот это?

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +            film.setLikes(selectLikes(id));
для того чтобы достать `mpa, genres, likes` мы делаем запрос на каждый фильм, что может быть очень накладно с точки зрения производительности. Стоит воспользоваться оператором `join` и делать все за один запрос

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +            film.setLikes(selectLikes(id));
один запрос

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +            return foundFilm.orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Фильм не найден"));
не очень понятно зачем это нужно

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    }
Для `MPA` стоит завести свой `storage` и свой объект `MPA`. Аналогичную работу необходимо проделать для жанров

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        }
Необходимо сохранить лайк в СУБД, здесь этого не происходит

2024-04-25 09:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDBStorage.java
> +public class UserDBStorage implements UserStorage {
Замечания аналогичные `FilmDbStorage`

2024-04-26 13:41 UTC, xakepon commented on src/main/resources/schema.sql
> +INSERT INTO motion_picture_association (MPA_name) VALUES
выполнено

2024-04-26 13:41 UTC, xakepon commented on src/main/resources/schema.sql
> +INSERT INTO genres (genre_name) VALUES
выполнено

2024-04-26 13:42 UTC, xakepon commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS genres, MPA_ids, film, motion_picture_association, film_genres, users, likes, friends;
это для тестов постмана, пока закоменчу тогда

2024-04-26 13:44 UTC, xakepon commented on src/main/resources/schema.sql
> +    MPA_name varchar
выполнено

2024-04-26 14:21 UTC, xakepon commented on src/main/resources/schema.sql
> +    MPA_id integer
выполнено

2024-04-26 14:23 UTC, xakepon commented on src/main/resources/schema.sql
> +    mpa_id integer,
выполнено

2024-04-26 14:26 UTC, xakepon commented on src/main/resources/schema.sql
> +);
выполнено

2024-04-26 14:33 UTC, xakepon commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_genres (
первичный ключ не применим к текущей реализации, ограничения реализовал, постараюсь сделать первичный ключ в ближайшее время, так как надо добавить отдельное поле в структуре данной базы

2024-04-26 14:40 UTC, xakepon commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
выполнено

2024-04-26 14:54 UTC, xakepon commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS likes (
ограничения добавил, поля уникальные из-за этого первичный ключ не делал

2024-04-26 14:58 UTC, xakepon commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS friends (
ограничения добавил, поля уникальные из-за этого первичный ключ не делал

2024-04-26 14:59 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/validate/ErrorHandler.java
> +    //@ResponseStatus(HttpStatus.BAD_REQUEST)
выполнено

2024-04-26 15:01 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Override
выполнено

2024-04-26 15:21 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        return updatedFilm.orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));
убрал

2024-04-26 15:22 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        checkFilm(film.getId());
если правильно понял то сделал

2024-04-26 15:27 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +            return foundFilm.orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Фильм не найден"));
убрал

2024-05-02 08:28 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-05-03 18:00 UTC, merged